Repository allez-chauffe/marcel, pull requests merged in 2019-06, with the labels that each got.

#341 :card_file_box: Put all in bolt...
  .dockerignore
  api/api.go
  api/api_test.go
  api/clients/client.go
  api/clients/clientmanager.go
  api/clients/clientservice.go
  api/clients/utils.go
  api/clients/wsclient.go
  api/containers/containermanager.go
  api/data/plugins.example.json
  api/db/clients/client.go
  api/db/clients/clients.go
  api/db/medias/media.go
  api/db/medias/medias.go
  api/db/plugins/plugin.go
  api/db/plugins/plugins.go
  api/db/users/users.go
  api/medias/media_test.go
  api/medias/mediaconfiguration.go
  api/medias/mediamanager.go
  api/medias/mediamanager_test.go
  api/medias/mediaservice.go
  api/plugins/git.go
  api/plugins/plugin.go
  api/plugins/plugin_test.go
  api/plugins/pluginmanager_test.go
  api/plugins/pluginservice.go
  api/plugins/pluginservice_test.go
  cmd/api.go
  config/config.go
  frontend/src/components/Client.js
Labels: technical

#342 :fire: Remove swagger and unused manager...
  api/README.md
  api/api.go
  api/apidoc/doc.go
  api/apidoc/swaggerservice.go
  api/commons/manager.go
  api/db/medias/media.go
  api/db/plugins/plugin.go
  api/medias/doc.go
  api/medias/mediaservice.go
  api/plugins/doc.go
  api/plugins/pluginservice.go
  api_doc/Makefile
  api_doc/README.md
  api_doc/main.go
  api_doc/swagger-ui/favicon-16x16.png
  api_doc/swagger-ui/favicon-32x32.png
  api_doc/swagger-ui/index.html
  api_doc/swagger-ui/oauth2-redirect.html
  api_doc/swagger-ui/swagger-ui-bundle.js
  api_doc/swagger-ui/swagger-ui-bundle.js.map
  api_doc/swagger-ui/swagger-ui-standalone-preset.js
  api_doc/swagger-ui/swagger-ui-standalone-preset.js.map
  api_doc/swagger-ui/swagger-ui.css
  api_doc/swagger-ui/swagger-ui.css.map
  api_doc/swagger-ui/swagger-ui.js
  api_doc/swagger-ui/swagger-ui.js.map
Labels: backend, chore

#343 :sparkles: Import / Export
  api/api.go
  api/commons/commons.go
  api/commons/commons_test.go
  api/db/db.go
  api/db/export/all.go
  api/db/export/export.go
  api/db/export/medias.go
  api/db/export/plugins.go
  api/db/export/users.go
  api/db/imp0rt/all.go
  api/db/imp0rt/imp0rt.go
  api/db/imp0rt/medias.go
  api/db/imp0rt/plugins.go
  api/db/imp0rt/users.go
  api/db/medias/medias.go
  api/db/plugins/plugins.go
  api/db/users/users.go
  cmd/api.go
  cmd/export.go
  cmd/import.go
  cmd/marcel.go
  main.go
Labels: WIP, backend

#321 :construction_worker: Push docker images only for master and tags
  .circleci/config.yml
  scripts/docker_build.sh
Labels: technical

#322 :construction_worker: Add script to install on multiple GCP environments
  .circleci/config.yml
  scripts/install.sh
Labels: technical
